import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex items-center gap-[15px] fixed top-[30px] left-1/2 translate-x-[-50%] bg-white text-black py-[15px] px-[30px] rounded-full">
          <Link href="/">Counter</Link>
          <Link href="/age">Age</Link>
          <Link href="/tabs">Tabs</Link>
          <Link href="/modal">Modal</Link>
          <Link href="/table">Table</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
